name: Test on multiple platforms

on:
  push:
    branches: [ "master", "ci-cd" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test_multiplatform:
    name: Build and test on ${{ matrix.os }} with ${{ matrix.c_compiler }} and ${{ matrix.cpp_compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        c_compiler: [cl, clang, gcc]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: gcc

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake Release Preset
        run: cmake --preset release_preset

      - name: Build Release Preset
        run: cmake --build --preset release_preset_build

      - name: Test
        run: ctest --preset run_tests_release
